#! /usr/bin/env bash
set -e

# Directory for build project Jekyll
build_dir="./test"

# Clone gh-pages test
git clone https://github.com/williamcanin/jekyll-spotify-plugin.git "$build_dir"

# Enter folder build
cd "$build_dir"

# Set branch website
git checkout website-code

# Dependencies download
bundle install

# Build project (website) with Jekyll Spotify Plugin.
bundle exec jekyll b

# Remove folder build
rm -rf "$build_dir"

printf "\nDone!\n"

