source 'https://rubygems.org'

# Specify your gem's dependencies in jekyll-spotify.gemspec
gemspec

# if ENV["JEKYLL_VERSION"]
#   gem "jekyll", "~> #{ENV["JEKYLL_VERSION"]}"
# end

gem "bundler"
gem "rake"
gem "jekyll"